// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAizMHQtvKqEiFQm9Ftsi07YZZlraBb4Gk',
    appId: '1:447541530000:web:e21a28a57ec9e838f0f715',
    messagingSenderId: '447541530000',
    projectId: 'learnova-f92fd',
    authDomain: 'learnova-f92fd.firebaseapp.com',
    storageBucket: 'learnova-f92fd.firebasestorage.app',
    measurementId: 'G-ZCF8EGE33W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoxIGH6exuWDICl8NaGT3QzHgvf0ZE4sA',
    appId: '1:447541530000:android:f5dfa76d411c5bddf0f715',
    messagingSenderId: '447541530000',
    projectId: 'learnova-f92fd',
    storageBucket: 'learnova-f92fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqExpl24UabmjuDMog9MT-QVrKGSoCChY',
    appId: '1:447541530000:ios:2e8bb221feab1742f0f715',
    messagingSenderId: '447541530000',
    projectId: 'learnova-f92fd',
    storageBucket: 'learnova-f92fd.firebasestorage.app',
    iosBundleId: 'com.example.learnova',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqExpl24UabmjuDMog9MT-QVrKGSoCChY',
    appId: '1:447541530000:ios:2e8bb221feab1742f0f715',
    messagingSenderId: '447541530000',
    projectId: 'learnova-f92fd',
    storageBucket: 'learnova-f92fd.firebasestorage.app',
    iosBundleId: 'com.example.learnova',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAizMHQtvKqEiFQm9Ftsi07YZZlraBb4Gk',
    appId: '1:447541530000:web:988c855f63b3d891f0f715',
    messagingSenderId: '447541530000',
    projectId: 'learnova-f92fd',
    authDomain: 'learnova-f92fd.firebaseapp.com',
    storageBucket: 'learnova-f92fd.firebasestorage.app',
    measurementId: 'G-C46E6N05MY',
  );
}
